config/routes.rb
Pahm250::Application.routes.draw do
  
  devise_for :users

  resources :questions do
    resources :answers
  end
  
    resources :exams do

       collection do
         get 'testpaper'
         post 'testpapernext'
         get 'testscore'
       end

    end
  

  root :to => 'exams#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  
  belongs_to :question 
  
  validates :answer, :presence => true
  
  
end

app/models/answers.rb
class Answer < ActiveRecord::Base
  
  belongs_to :question 
  
  validates :answer, :presence => true
  
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  
    has_many :answers, :dependent => :destroy
    accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:answer].blank? }, :allow_destroy => true

    validates :question, :presence => true
    validates :hint, :presence => true

  #  private

    def self.generate_random
      @a ||= (1..600).to_a.shuffle[1,75]
    end
    
    
end

app/models/questions.rb
class Question < ActiveRecord::Base
  
    has_many :answers, :dependent => :destroy
    accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:answer].blank? }, :allow_destroy => true

    validates :question, :presence => true
    validates :hint, :presence => true

  #  private

    def self.generate_random
      @a ||= (1..600).to_a.shuffle[1,75]

    end
    
    
end

app/models/quiz_option.rb
class QuizOption < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :ok }
    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  
  
  before_filter :exam_question_list, :authenticate_user!
  
  def index
    @_array = session[:array]
    @questions = Question.find(@_array)
    QuizOption.find_by_user_id(current_user).destroy
    respond_to do |format|
      format.html # index.html.erb
      format.json { head :ok }
    end    
  end
  
  def testpaper
    @quiz_option = QuizOption.new
#    @_array = session[:array]
    @questions = Question.find(session[:array])
    @questions =  Kaminari.paginate_array(@questions).page(params[:page]).per(1)
    
    respond_to do |format|
      format.html # testpaper.html.erb
      format.json { render json: @question }   
    end  
  end

  def testpapernext

    @_quiz_option_array = params[:quiz_option]
    @question_option = @_quiz_option_array["question"]
    
    @question = Question.find(@question_option)
    
    @quiz_option = QuizOption.find_by_question(@question_option)
    
    if @quiz_option.nil?
      @quiz_option = QuizOption.new(params[:quiz_option])
      @quiz_option.save
      session[:quiz_option_count] += 1
    else
      @quiz_option.update_attributes(params[:quiz_option])
    end
    
    @answer =  @question.answers.find(@_quiz_option_array[:answer])
    if @answer.correct
      @quiz_option.update_attributes(:correct => true)
      @question.increment!(:right, by=1)
    else
      @quiz_option.update_attributes(:correct => false)
      @question.increment!(:wrong, by=1)
    end
#    @_array = session[:array]
#    session[:array] = @_array.drop(1)
    @quiz_option_count = QuizOption.count
    if (@quiz_option_count >= 75)
      flash[:notice] = "Well done! You hace successfully completed the test please press link below for test score results"
      session[:quiz_option_count] = @quiz_option_count
    else
      flash[:notice] = "Option is updated, click Next_Question"
    end
    
    redirect_to :back
  end
  
  def testscore
    @quiz_option_count_correct = QuizOption.count(:conditions => {:correct => true})
    @_quiz_option_test_array = params[:quiz_option]
    @_quiz_option_question = Question.find(@_quiz_option_test_array)
    
    respond_to do |format|
      format.html # testscore.html.erb
      format.json { head :ok }
    end
  end 
       
  private 
  
  def exam_question_list    
  session[:array] ||= Question.generate_random
  end  
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
#  before_filter :authorize
   before_filter :authenticate_user!
   
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new
    3.times { @question.answers.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :ok }
    end
  end
 

    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/exams/_form.html.erb
<% @questions.each do |question| %>

<p>
  <strong>Question:</strong>
  <%= question.question %>
</p>

<% @quiz_option_selected = QuizOption.find_by_question(question.id) %>
	

	<%= form_for @quiz_option, :url => { :action => "testpapernext"} do |f| %>
		
		<div class="field">
	    <%= f.hidden_field :question, :value => question.id %>
	    </div>
	   
		<div class="field">
	    <%= f.hidden_field :user_id, :value => current_user.id %>
	    </div>
	
		<% for ans in question.answers %>
		<br/>
		<div class="field">
			
			<% if @quiz_option_selected.nil? %>
			    <%= f.radio_button :answer, ans.id %>
			<% else %>
				<% if @quiz_option_selected.answer == ans.id %>
					<%= f.radio_button :answer, ans.id , :checked => true %>
					<% else %>	
					<%= f.radio_button :answer, ans.id %>
				<% end %>
			<% end %>
			
			<%=h ans.answer%>
			
		</div>
			
		<% end %>
		<br/>
		<br/>
		
		<div class="actions">
				<div class="input-prepend">
					<span class="add-on"><i class="icon-check"></i></span>
					<%= f.submit "Confirm Option", :class => "btn" %>		
				</div>
	    </div>
		
	<% end %>
	
<% end %>

app/views/exams/index.html.erb
<div class="hero-unit">

<h1>PAHM-250 MOCK TEST</h1>
<p>Hi this is a mockup test for pahm-250 certificate course. This is a multiple choice based exam on all the business related topics of the health industry. the test will contain a set of 75 questions. The exam will be a duration of 75 min.</p>

<h3>Best of luck........ press below to take test</h3>
<br/>
<br/>
<a>
<%= link_to '>> BEGIN TEST NOW >>', testpaper_exams_path, :class=> "btn btn-primary btn-large" %>
</a>

</div>

app/views/exams/testpaper.html.erb
<% if flash[:notice] %>
	<%= paginate @questions %>
<% end %>


<%= render 'form' %>

<br/>
<br/>
<br/>
<% if session[:quiz_option_count] %>

	<% if (session[:quiz_option_count] >= 75) %>
		<%= link_to 'Test Score', testscore_exams_path, :class => "btn btn-primary btn-large" %>
	<% end %>
	
<% end %>

app/views/exams/testscore.html.erb
<div class="hero-unit">

	<h1>Congratulations !!</h1>
	<br/>
	<br/>
	<p> You have completed the test your score is : <%= @quiz_option_count_correct %> out of 75 </p> 
	<br/>
	<br/>
	<h3> These are the options you selected for each question </h3>
	<br/>
	<% for question in @_quiz_option_question %>
		<p> 
			<b><%=h question.question %></b>
			<% @quiz_option_selected = QuizOption.find_by_question(question.id) %>
			<% if @quiz_option_selected.correct %>
			<b> <%= image_tag "correct.gif" %> </b>
			<% else %>
			<b> <%= image_tag "wrong.gif" %> </b>
			<% end %>			
		</p>
	<% end %>
	
	<br/>
	<p> Your score card will be mailed to your email id <%= current_user.email %> .... shortly </p>
	<br/>
	<p>Please press here <%= link_to "take test again", testpaper_exams_path %> if you want to retake the test or press here for ... <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PAHM-250</title>
	<!-- [if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
		type="text/javascript"></script>
	<![endif]-->
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
 	<meta name="viewport" content="width=device-width, intial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="brand" href="#">PAHM-250 MOCKTEST</a>
			<ul class="nav pull-right">
			  <li class="active">
			 <li class="divider-vertical"></li>
				<% if user_signed_in? %>
				<a href="#">Signed in as <%= current_user.email%>. Not You ? </a>
					<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			  </li>
				<% else %>
					<li class="divider-vertical"></li>
					<li><%= link_to "Sign up", new_user_registration_path %></li>
					<li class="divider-vertical"></li>
					<li><%= link_to "Sign in", new_user_session_path%></li>
					<li class="divider-vertical"></li>
				<% end %>
			</ul>
	    </div>
	  </div>
	</div>
	<div class="container">
	  <div class="row">
		<div class="span7 offset2">
		<% if flash[:notice] %>
			<div class="alert alert-success">
			  <%= notice %>
			</div>
	    <% end %>
		<% if flash[:alert] %>
			<div class="alert alert-error">
			<%= alert %>
			</div>
		<% end %>	
		<%= yield %>
		</div>
		<div class="span3">
			<address>
			<h2> Test Site ! </h2><br>			
			This is beta site made for the CGI employees and other professionals who are preparing for
the PAHM-250 introductory course exam. Most of the questions in the database are collected by peer feedback. As the original exam course is continuously updated. Please drop in a mail at webmaster to update the question bank.
			</address>
		    <address>
			  </p>
			<strong>Copyright @ Salman Ahmed 2012 </strong><br>
			<p>webmaster: <a href="mailto:#">milleniumsalman@gmail.com</a></p>	
			</address>	
		</div>
	  </div>
	</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Question</legend>

    <div class="control-group">
      <%= f.label :question, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :question, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :right, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :right, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :wrong, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :wrong, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :difficulty, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :difficulty, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :chapter, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :chapter, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :hint, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :hint, :rows => 3, :class => 'text_area' %>
      </div>
    </div>

	<table class="table">
		<thead>
	    <tr>
	      <th>Answers as given below</th>
	      <th>Correct option is marked</th>
	    </tr>
	  </thead>
	  <tbody>
		<%= f.fields_for :answers do |answer_form| %>
		<tr>
		<td>
		<div class="control-group">			
			<div class="controls">
				<%= answer_form.text_field :answer, :class => 'text_field' %>
			</div>	
		</div>
		</td>
		<td>
		<div class="control-group">
			<div class="controls">
				<%= answer_form.check_box :correct, :class => 'checkbox_field' %>
			</div>
		</div>
		</td>
		</tr>
		<% end %>
	</table>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', questions_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/questions/edit.html.erb
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Question</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= link_to question.question, question_path(question) %></td>
        <td><%= question.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_question_path(question), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', question_path(question), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_question_path, :class => 'btn btn-primary' %>

app/views/questions/new.html.erb
<%= render :partial => 'form' %>

app/views/questions/show.html.erb
<h1>Question</h1>

<p>
  <b>Question</b><br>
  <%= @question.question %>
</p>

<p>
  <b>Right</b><br>
  <%= @question.right %>
</p>

<p>
  <b>Wrong</b><br>
  <%= @question.wrong %>
</p>

<p>
  <b>Difficulty</b><br>
  <%= @question.difficulty %>
</p>

<p>
  <b>Chapter</b><br>
  <%= @question.chapter %>
</p>

<p>
  <b>Hint</b><br>
  <%= @question.hint %>
</p>

<% for ans in @question.answers %>
<p>
	<b> Answer  || Option (True/False)</b></br>
	<%=h ans.answer%>
	<b> || </b>
	<%=h ans.correct%>	
</p>
<% end %>



<div class="form-actions">
  <%= link_to 'Back', questions_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_question_path(@question), :class => 'btn' %>
  <%= link_to 'Delete', question_path(@question), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>